spring:
  application:
    name: dividend-financial
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    defer-datasource-initialization: true
    database-platform: H2
    hibernate:
      ddl-auto: create
      use-new-id=generator-mappings: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  redis:
    host: localhost
    port: 6379
  jwt:
    secret: ZGF5b25lLXNwcmluZy1ib290LWRpdmlkZW5kLXByb2plY3QtdHV0b3JpYWwtand0LXNlY3JldC1rZXk=

scheduler:
  scrap:
    yahoo: "0 0 0 * * *"